In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

In [2]:
df= pd.read_csv(r'D:\women_detection\womens_safety_filtered_data.csv')

In [3]:
df

,Latitude,Longitude,CrimeGroup_Name,FIR_MONTH,FIR_Day,District_Name,UnitName,Female,Girl
0,NaN,NaN,POCSO,1,5,Bagalkot,Amengad PS,0,1
1,NaN,NaN,MOTOR VEHICLE ACCIDENTS FATAL,1,18,Bagalkot,Amengad PS,1,0
2,NaN,NaN,CRUELTY BY HUSBAND,1,31,Bagalkot,Amengad PS,1,0
3,NaN,NaN,MOTOR VEHICLE ACCIDENTS FATAL,2,10,Bagalkot,Amengad PS,1,0
4,NaN,NaN,MOTOR VEHICLE ACCIDENTS FATAL,2,15,Bagalkot,Amengad PS,1,0
...,...,...,...,...,...,...,...,...,...
380834,16.748633,77.133669,MISSING PERSON,1,11,Yadgir,Yadgiri Women PS,1,0
380835,16.844536,77.021722,POCSO,1,29,Yadgir,Yadgiri Women PS,0,1
380836,16.556974,77.159238,MOLESTATION,2,7,Yadgir,Yadgiri Women PS,1,0
380837,16.772232,77.117018,CRIMES RELATED TO WOMEN,2,24,Yadgir,Yadgiri Women PS,1,0
380838,16.800526,77.141569,KIDNAPPING AND ABDUCTION,2,28,Yadgir,Yadgiri Women PS,0,1

In [4]:
df.head()

,Latitude,Longitude,CrimeGroup_Name,FIR_MONTH,FIR_Day,District_Name,UnitName,Female,Girl
0,NaN,NaN,POCSO,1,5,Bagalkot,Amengad PS,0,1
1,NaN,NaN,MOTOR VEHICLE ACCIDENTS FATAL,1,18,Bagalkot,Amengad PS,1,0
2,NaN,NaN,CRUELTY BY HUSBAND,1,31,Bagalkot,Amengad PS,1,0
3,NaN,NaN,MOTOR VEHICLE ACCIDENTS FATAL,2,10,Bagalkot,Amengad PS,1,0
4,NaN,NaN,MOTOR VEHICLE ACCIDENTS FATAL,2,15,Bagalkot,Amengad PS,1,0